# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-16 15:04
from __future__ import unicode_literals

import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists'}, help_text='Required. 150 words or fewer. Letter, digits, and @/./+/-/_ only', max_length=150, unique=True, validators=[django.contrib.auth.validators.ASCIIUsernameValidator()], verbose_name='username')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('first_name', models.CharField(max_length=50, verbose_name='first name')),
                ('middle_name', models.CharField(blank=True, max_length=50, verbose_name='middle name')),
                ('last_name', models.CharField(blank=True, max_length=50, verbose_name='last name')),
                ('email', models.CharField(error_messages={'unique': 'Provided email-id already exists.'}, max_length=255, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='email address')),
                ('is_active', models.BooleanField(default=False, verbose_name='active')),
                ('reset_code', models.CharField(max_length=255, verbose_name='reset code')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
