# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-17 07:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('access_token', models.CharField(default=uuid.uuid4, max_length=255)),
                ('expires_at', models.DateTimeField(default=datetime.datetime(2017, 12, 19, 7, 41, 19, 838181))),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
            options={
                'db_table': 'user_token',
            },
        ),
    ]
